###
# Updates apt
# Installs packages
# Enables firewall
##
- apt: update_cache=yes
  sudo: yes

- name: ensure web server packages are installed
  apt: name={{item}}
  sudo: yes
  with_items:
    - fail2ban
    - python-virtualenv
    - python-dev

- name: enable SSH in firewall
  ufw: rule=allow port=22
  sudo: yes
- name: enable HTTP connection
  ufw: rule=allow port=80
  sudo: yes
- name: enable HTTPS connection
  ufw: rule=allow port=443
  sudo: yes
- name: enable firewall
  ufw: state=enabled
  sudo: yes

